Repository ZonalWings/hotfoot, pull requests merged in 2020-05, with the labels that each got.

#113 Update/login ui
  fonts/Montserrat-Regular.ttf
  lib/core/style/style.dart
  lib/features/location/presentation/ui/location_form.dart
  lib/features/login/presentation/ui/screen/splash_screen.dart
  lib/features/login/presentation/ui/widgets/create_account_button.dart
  lib/features/login/presentation/ui/widgets/login_button.dart
  lib/features/login/presentation/ui/widgets/login_form.dart
  lib/features/navigation_home/presentation/ui/widgets/runs_tab.dart
  lib/features/places/presentation/ui/widgets/place_card.dart
  lib/features/registration/presentation/ui/widgets/registration_button.dart
  lib/features/registration/presentation/ui/widgets/registration_form.dart
  lib/features/runs/presentation/ui/widgets/place_name.dart
  lib/features/runs/presentation/ui/widgets/place_run_button.dart
  lib/features/runs/presentation/ui/widgets/run_card.dart
  lib/features/runs/presentation/ui/widgets/run_form.dart
  lib/features/user/presentation/ui/screens/settings_screen.dart
  lib/features/user/presentation/ui/widgets/user_type_widget.dart
  pubspec.yaml
Labels: enhancement

#117 Run user details
  lib/features/run_map/presentation/blocs/other_user_details/other_user_details_bloc.dart
  lib/features/run_map/presentation/blocs/other_user_details/other_user_details_event.dart
  lib/features/run_map/presentation/blocs/other_user_details/other_user_details_state.dart
  lib/features/run_map/presentation/ui/widgets/more_info_speed_dial.dart
  lib/features/run_map/presentation/ui/widgets/order_details_popup.dart
  lib/features/run_map/presentation/ui/widgets/run_map.dart
  lib/features/run_map/presentation/ui/widgets/run_map_widget.dart
  lib/features/run_map/presentation/ui/widgets/user_details_popup.dart
  lib/features/run_placed/presentation/ui/screen/run_placed_screen.dart
  lib/features/user/data/data_sources/user_remote_data_source.dart
  lib/features/user/data/repositories/user_repositories_impl.dart
  lib/features/user/domain/repositories/user_repository.dart
  lib/features/user/domain/use_cases/get_user_info_by_id.dart
  lib/injection_container.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#121 Funds and cost
  lib/features/run_map/presentation/ui/widgets/more_info_speed_dial.dart
  lib/features/run_map/presentation/ui/widgets/order_details_popup.dart
  lib/features/run_placed/presentation/blocs/qr_code/qr_code_bloc.dart
  lib/features/runs/presentation/ui/screens/accept_run_screen.dart
  lib/features/runs/presentation/ui/widgets/cost_confirmation_popup.dart
  lib/features/runs/presentation/ui/widgets/run_form.dart
  lib/features/user/data/models/user_model.dart
  lib/features/user/data/repositories/user_repositories_impl.dart
  lib/features/user/domain/entities/user_entity.dart
  lib/features/user/domain/repositories/user_repository.dart
  lib/features/user/domain/use_cases/add_user_funds.dart
  lib/features/user/domain/use_cases/get_user_funds.dart
  lib/features/user/domain/use_cases/subtract_user_funds.dart
  lib/features/user/presentation/blocs/user_funds/user_funds_bloc.dart
  lib/features/user/presentation/blocs/user_funds/user_funds_event.dart
  lib/features/user/presentation/blocs/user_funds/user_funds_state.dart
  lib/features/user/presentation/ui/screens/settings_screen.dart
  lib/features/user/presentation/ui/widgets/add_funds_popup.dart
  lib/features/user/presentation/ui/widgets/user_funds_widget.dart
  lib/injection_container.dart
  pubspec.lock
Labels: enhancement

#124 123 - Add photo to run cards
  lib/features/runs/presentation/ui/widgets/run_card.dart
  lib/features/runs/presentation/ui/widgets/run_list_tile.dart
Labels: enhancement

#127 125 - Add place photo to accept run screen
  lib/features/runs/presentation/ui/screens/accept_run_screen.dart
  lib/features/runs/presentation/ui/widgets/run_photo.dart
Labels: enhancement

#126 Update/chat section
  lib/features/run_placed/presentation/ui/widgets/active_run_info_widget.dart
  lib/features/run_placed/presentation/ui/widgets/cancel_delivery_button.dart
  lib/features/run_placed/presentation/ui/widgets/chat_message_list_item.dart
  lib/features/run_placed/presentation/ui/widgets/chat_section.dart
  lib/features/run_placed/presentation/ui/widgets/open_close_chat_button.dart
  lib/features/run_placed/presentation/ui/widgets/qr_code.dart
  lib/features/run_placed/presentation/ui/widgets/qr_scanner_button.dart
  lib/features/run_placed/presentation/ui/widgets/status_bar.dart
Labels: enhancement

#129 128 - Add customer avatar to accept run screen
  lib/features/runs/presentation/ui/screens/accept_run_screen.dart
Labels: enhancement

#131 User ratings
  lib/features/run_placed/presentation/blocs/qr_code/qr_code_bloc.dart
  lib/features/run_placed/presentation/blocs/run_finalizer/run_finalizer_bloc.dart
  lib/features/run_placed/presentation/blocs/run_finalizer/run_finalizer_event.dart
  lib/features/run_placed/presentation/blocs/run_finalizer/run_finalizer_state.dart
  lib/features/run_placed/presentation/ui/screen/run_placed_screen.dart
  lib/features/run_placed/presentation/ui/widgets/give_rating_popup.dart
  lib/features/user/data/data_sources/user_remote_data_source.dart
  lib/features/user/data/models/ratings_model.dart
  lib/features/user/data/models/user_model.dart
  lib/features/user/data/repositories/user_repositories_impl.dart
  lib/features/user/domain/entities/ratings_entity.dart
  lib/features/user/domain/entities/user_entity.dart
  lib/features/user/domain/repositories/user_repository.dart
  lib/features/user/domain/use_cases/add_customer_rating.dart
  lib/features/user/domain/use_cases/add_runner_rating.dart
  lib/features/user/domain/use_cases/get_user_ratings.dart
  lib/features/user/presentation/blocs/user_ratings/user_ratings_bloc.dart
  lib/features/user/presentation/blocs/user_ratings/user_ratings_event.dart
  lib/features/user/presentation/blocs/user_ratings/user_ratings_state.dart
  lib/features/user/presentation/ui/screens/settings_screen.dart
  lib/features/user/presentation/ui/widgets/user_ratings_widget.dart
  lib/injection_container.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#130 118 - auto login now possible
  lib/features/registration/data/repositories/registration_repository_impl.dart
  lib/features/user/domain/entities/user_entity.dart
Labels: enhancement

#136 Update/ui/order again modal
  lib/features/runs/presentation/ui/widgets/cost_confirmation_popup.dart
  lib/features/runs/presentation/ui/widgets/run_card.dart
  lib/features/user/domain/entities/user_entity.dart
Labels: enhancement

#133 Feature/active run
  lib/app.dart
  lib/features/run_placed/presentation/blocs/qr_code/qr_code_bloc.dart
  lib/features/run_placed/presentation/ui/widgets/status_bar.dart
  lib/features/runs/data/data_sources/runs_remote_data_source.dart
  lib/features/runs/data/repositories/runs_repositories_impl.dart
  lib/features/runs/domain/entities/run_status.dart
  lib/features/runs/domain/repositories/runs_repository.dart
  lib/features/runs/domain/use_cases/get_active_run.dart
  lib/features/runs/presentation/blocs/accept_run/accept_run_bloc.dart
  lib/features/runs/presentation/blocs/active_run/active_run_bloc.dart
  lib/features/runs/presentation/blocs/active_run/active_run_event.dart
  lib/features/runs/presentation/blocs/active_run/active_run_state.dart
  lib/features/runs/presentation/ui/widgets/run_card.dart
  lib/injection_container.dart
  lib/main.dart
Labels: enhancement

#139 Fixes/minor bugs
  lib/features/run_placed/presentation/ui/widgets/cancel_delivery_button.dart
  lib/features/run_placed/presentation/ui/widgets/chat_message_list_item.dart
  lib/features/run_placed/presentation/ui/widgets/chat_section.dart
  lib/features/user/data/data_sources/user_local_data_source.dart
  lib/features/user/data/repositories/user_repositories_impl.dart
  lib/features/user/presentation/ui/widgets/user_photo_widget.dart
  lib/injection_container.dart
Labels: bug_fix

#140 136 - now parses name parameter for usermodel
  lib/features/user/data/data_sources/user_remote_data_source.dart
Labels: enhancement

#142 141 - Forward Runner App to Active Run
  lib/features/runs/data/data_sources/runs_remote_data_source.dart
Labels: bug_fix

#143 141 - changed where sender's name is parsed
  lib/features/run_placed/presentation/ui/widgets/chat_message_list_item.dart
  lib/features/run_placed/presentation/ui/widgets/chat_section.dart
Labels: enhancement

#145 Update/settings scr displayname
  lib/core/util/util.dart
  lib/features/run_placed/presentation/ui/widgets/chat_section.dart
  lib/features/user/data/data_sources/user_remote_data_source.dart
  lib/features/user/presentation/ui/screens/settings_screen.dart
Labels: enhancement

#146 144 - Add avatar to user detail pop up
  lib/features/run_map/presentation/ui/widgets/user_details_popup.dart
Labels: enhancement

#148 147 - updated app bar fonts to match rest of app
  lib/features/login/presentation/ui/screen/login_screen.dart
  lib/features/navigation_home/presentation/ui/widgets/home_tab.dart
  lib/features/navigation_home/presentation/ui/widgets/runs_tab.dart
  lib/features/registration/presentation/ui/screen/registration_screen.dart
  lib/features/run_placed/presentation/ui/screen/run_placed_screen.dart
  lib/features/run_placed/presentation/ui/widgets/chat_section.dart
  lib/features/runs/presentation/ui/screens/accept_run_screen.dart
  lib/features/runs/presentation/ui/screens/run_details_screen.dart
  lib/features/search/presentation/ui/screens/search_handler_screen.dart
  lib/features/search/presentation/ui/screens/unknown_place_screen.dart
  lib/features/search/presentation/ui/widgets/search_bar.dart
  lib/features/search/presentation/ui/widgets/search_bottom_drawer.dart
  lib/features/user/presentation/ui/screens/settings_screen.dart
Labels: enhancement

#149 147 - Get correct user id for photo
  lib/features/user/data/data_sources/user_local_data_source.dart
  lib/features/user/presentation/ui/widgets/user_photo_widget.dart
  lib/injection_container.dart
Labels: bug_fix

#152 151 - Get photo from remote repo if possible
  lib/features/user/data/repositories/user_repositories_impl.dart
Labels: enhancement

#154 153 - Toggle Switch Colors
  lib/features/user/presentation/ui/widgets/user_type_toggle_switch.dart
Labels: enhancement

#156 Ui fixes run map
  assets/destination_marker.png
  assets/pickup_marker.png
  assets/runner_marker.png
  lib/features/run_map/presentation/blocs/runner_location/runner_location_bloc.dart
  lib/features/run_map/presentation/ui/widgets/user_details_popup.dart
  lib/features/run_placed/presentation/ui/screen/run_placed_screen.dart
  lib/features/run_placed/presentation/ui/widgets/other_user_cancelled_popup.dart
  pubspec.yaml
Labels: enhancement

#157 Revert "151 - Get photo from remote repo if possible"
  lib/features/user/data/repositories/user_repositories_impl.dart
Labels: bug, bug_fix

#159 158 - made fonts for entire app uniform
  lib/core/style/style.dart
  lib/features/login/presentation/ui/widgets/login_form.dart
  lib/features/navigation_home/presentation/ui/widgets/bottom_nav_bar.dart
  lib/features/navigation_home/presentation/ui/widgets/home_tab.dart
  lib/features/navigation_home/presentation/ui/widgets/runs_tab.dart
Labels: enhancement
