Repository ZonalWings/hotfoot, pull requests merged in 2020-03, with the labels that each got.

#35 Feature/firebase login
  lib/src/app.dart
  lib/src/blocs/login_bloc/login_form.dart
  lib/src/blocs/register_bloc/register_form.dart
  lib/src/utils/validators.dart
Labels: enhancement

#39 38 - Catch API keys precommit in githook
  .githooks/pre-commit
Labels: testing

#37 Countinous Integration for Hotfoot
  .github/workflows/android-debug-run.yaml
  .github/workflows/android-release-build.yaml
  .github/workflows/flutter_test.yaml
  .github/workflows/ios-debug-run.yaml
  .github/workflows/ios-simulator-build.yaml
  README.md
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Flutter.podspec
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  scripts/debug-run.sh
  test/example_test.dart
Labels: testing

#41 40 - Updated json file
  android/app/google-services.json
Labels: enhancement

#43 42 - Firebase config for iOS
  .github/workflows/android-release-build.yaml
  .gitignore
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
Labels: enhancement

#47 Feature/navigation
  lib/core/use_cases/use_case.dart
  lib/core/validators/validators.dart
  lib/features/login/presentation/ui/screen/splash_screen.dart
  lib/features/navigation_home/presentation/bloc/navigation_home_bloc.dart
  lib/features/navigation_home/presentation/bloc/navigation_home_event.dart
  lib/features/navigation_home/presentation/bloc/navigation_home_state.dart
  lib/features/navigation_home/presentation/ui/screen/home_screen.dart
  lib/features/navigation_home/presentation/ui/widgets/bottom_nav_bar.dart
  lib/features/navigation_home/presentation/ui/widgets/home_tab.dart
  lib/features/navigation_home/presentation/ui/widgets/orders_tab.dart
  lib/features/navigation_home/presentation/ui/widgets/search_tab.dart
  lib/features/navigation_screen/presentation/bloc/navigation_screen_bloc.dart
  lib/features/navigation_screen/presentation/bloc/navigation_screen_event.dart
  lib/features/navigation_screen/presentation/bloc/navigation_screen_state.dart
  lib/injection_container.dart
  lib/main.dart
  lib/src/app.dart
  lib/src/app_state.dart
  lib/src/screens/profile.dart
  lib/src/screens/request_run.dart
  lib/src/screens/request_run_screen.dart
  lib/src/screens/settings_screen.dart
Labels: enhancement

#51 Feature/chat
  lib/features/login/presentation/ui/widgets/login_form.dart
  lib/features/order_placed/presentation/ui/screen/order_placed_screen.dart
  lib/features/order_placed/presentation/ui/widgets/accept_delivery_button.dart
  lib/features/order_placed/presentation/ui/widgets/cancel_delivery_button.dart
  lib/features/order_placed/presentation/ui/widgets/chat_section.dart
  lib/features/order_placed/presentation/ui/widgets/open_close_chat_button.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#50 Feature/popular places
  assets/place-photo-placeholder.png
  lib/app.dart
  lib/core/database/app_database.dart
  lib/core/error/failures.dart
  lib/core/network/network_info.dart
  lib/features/navigation_home/presentation/ui/widgets/home_tab.dart
  lib/features/navigation_screen/presentation/bloc/navigation_screen_bloc.dart
  lib/features/navigation_screen/presentation/bloc/navigation_screen_event.dart
  lib/features/places/data/data_sources/data_access_objects/place_dao.dart
  lib/features/places/data/data_sources/data_access_objects/place_photo_dao.dart
  lib/features/places/data/data_sources/places_local_data_source.dart
  lib/features/places/data/data_sources/places_remote_data_source.dart
  lib/features/places/data/models/location_model.dart
  lib/features/places/data/models/place_model.dart
  lib/features/places/data/repositories/places_repositories_impl.dart
  lib/features/places/domain/entities/location_entity.dart
  lib/features/places/domain/entities/place_entity.dart
  lib/features/places/domain/repositories/places_repository.dart
  lib/features/places/domain/use_cases/get_place_by_id.dart
  lib/features/places/domain/use_cases/get_place_photo.dart
  lib/features/places/domain/use_cases/get_places_ids.dart
  lib/features/places/presentation/blocs/place_details/place_details_bloc.dart
  lib/features/places/presentation/blocs/place_details/place_details_event.dart
  lib/features/places/presentation/blocs/place_details/place_details_state.dart
  lib/features/places/presentation/blocs/place_photo/place_photo_bloc.dart
  lib/features/places/presentation/blocs/place_photo/place_photo_event.dart
  lib/features/places/presentation/blocs/place_photo/place_photo_state.dart
  lib/features/places/presentation/blocs/places_ids/places_ids_bloc.dart
  lib/features/places/presentation/blocs/places_ids/places_ids_event.dart
  lib/features/places/presentation/blocs/places_ids/places_ids_state.dart
  lib/features/places/presentation/ui/widgets/place_card.dart
  lib/features/places/presentation/ui/widgets/place_list.dart
  lib/features/places/presentation/ui/widgets/place_list_tile.dart
  lib/injection_container.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#54 53 - Login Keyboard Actions
  lib/features/login/presentation/ui/widgets/login_form.dart
Labels: bug_fix
